# Generated by Django 2.1 on 2019-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='наименование товара')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='описание')),
                ('category', models.CharField(choices=[('телефоны', 'smartphones'), ('весы', 'weights'), ('сувениры', 'souvenirs'), ('иное', 'others')], default='телефоны', max_length=40, verbose_name='Статус')),
                ('balance', models.PositiveIntegerField(blank=True, verbose_name='остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
            ],
        ),
    ]
