# Generated by Django 2.1 on 2019-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190924_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('иное', 'others'), ('телефоны', 'smartphones'), ('весы', 'weights'), ('сувениры', 'souvenirs')], default='иное', max_length=40, verbose_name='Категория'),
        ),
    ]
